apiVersion: v1
kind: Namespace
metadata:
  name: networking
  labels:
    gateway.internal/access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    gateway.internal/access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    gateway.internal/access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    gateway.internal/access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: identity
  labels:
    gateway.internal/access: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: idp-test
  labels:
    gateway.internal/access: 'true'
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: idp-staging
  labels:
    gateway.internal/access: 'true'
    pod-security.kubernetes.io/enforce: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    gateway.internal/access: 'true'
    pod-security.kubernetes.io/enforce: restricted
