#!/usr/bin/env bash
set -Eeuo pipefail
REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
log() { printf '%s\n' "$*" >&2; }
root_required() { [[ $EUID -eq 0 ]] || die 'Run this host provisioning script as root.'; }
debian_required() {
    # shellcheck source=/dev/null
    source /etc/os-release
    [[ $ID == debian && $VERSION_ID == 13 ]] || die 'These scripts require Debian 13 (trixie).'
    [[ $(dpkg --print-architecture) =~ ^(amd64|arm64)$ ]] || die 'Only amd64 and arm64 are supported by this cluster base.'
}
load_site() {
    [[ -r $REPO_ROOT/.local/site.env && -r $REPO_ROOT/.local/versions.env ]] || die 'Run python3 scripts/configure.py on this copy first.'
    # These files are generated by configure.py with shell-quoted values.
    # shellcheck source=/dev/null
    source "$REPO_ROOT/.local/site.env"
    # shellcheck source=/dev/null
    source "$REPO_ROOT/.local/versions.env"
}
download() { curl --fail --location --retry 3 --connect-timeout 15 --max-time 300 --silent --show-error "$1" -o "$2"; }
apt_prepare() {
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y ca-certificates curl gpg python3 python3-yaml openssl jq git
}
fresh_node_required() {
    [[ ! -e /var/lib/rancher/k3s/server/db && ! -e /etc/systemd/system/k3s-agent.service ]] ||
        die 'Existing k3s installation detected. Remove/rebuild explicitly; this is a fresh-node installer.'
}
