#!/usr/bin/env bash
set -Eeuo pipefail
source "$(dirname "$0")/lib/common.sh"
log 'Display controllers and active kernel drivers:'
lspci -nnk | grep -A3 -E 'VGA|3D|Display' || true
log 'DRM and compute device nodes:'
for path in /dev/dri/renderD* /dev/kfd /dev/nvidia*; do [[ ! -e $path ]] || stat -c '%A %U:%G %n' "$path"; done
if command -v nvidia-smi >/dev/null; then nvidia-smi; fi
if command -v rocminfo >/dev/null && [[ -e /dev/kfd ]]; then rocminfo; fi
if command -v clinfo >/dev/null; then clinfo --list; fi
if command -v k3s >/dev/null; then
    log 'Runtime handlers generated by k3s (after a service restart):'
    grep -E 'runtimes\.|BinaryName|enable_cdi' /var/lib/rancher/k3s/agent/etc/containerd/config.toml || true
fi
log 'Host preparation does not advertise GPU resources. Install the appropriate Kubernetes device plugin/operator next.'
